---
driver:
  name: docker
  hostname: hubblestack.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: hubblestack
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - hubblestack
  pillars:
    top.sls:
      base:
        "*":
          - hubblestack

verifier:
  name: inspec
  sudo: true


platforms:
  - name: <%=ENV['PLATFORM'] || 'ubuntu-xenial'%>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'trevorj/salty-whales:xenial'%>
      platform: ubuntu

suites:
  - name: default
    provisioner:
      pillars-from-files:
        hubblestack.sls: tests/pillar/hubblestack.sls
# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
